# .github/workflows/daily_scrape.yml

name: Daily Property Scrape

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    # Runs at 01:00 UTC every day (which is 6:30 AM in India)
    - cron: '0 1 * * *'

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the daily scrape script
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }} # Use the secret we set up on GitHub
        run: python run_daily_scrape.py
