name: Daily Property Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the daily scrape script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python run_daily_scrape.py
